name: Build and Test

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # Restore NuGet packages (update solution path)
      - name: Restore NuGet Packages
        run: nuget restore OrderProcessingWebApp/OrderProcessingSystem.sln

      # Build the solution with MSBuild (update solution path)
      - name: Build Solution
        run: msbuild OrderProcessingWebApp/OrderProcessingSystem.sln /p:Configuration=Release /p:Platform="Any CPU" /v:detailed

      # Run tests (if any)
      - name: Run Tests
        run: vstest.console.exe TestProject/bin/Release/TestProject.dll
