name: Build and Test

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Use Windows runner for .NET Framework

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # Restore NuGet packages using MSBuild
      - name: Restore NuGet Packages
        run: nuget restore OrderProcessingSystem.sln  # Ensure your solution file path is correct

      # Build the solution with MSBuild (for .NET Framework 4.8)
      - name: Build Solution
        run: msbuild OrderProcessingSystem.sln /p:Configuration=Release /p:Platform="Any CPU"  # Make sure this path is correct

      # Run Tests (if you have unit tests configured)
      #- name: Run Tests
      #  run: vstest.console.exe TestProject/bin/Release/TestProject.dll  # Adjust if your test project has a different path
